//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP.Properties
{
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ImportExportResources
	{
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ImportExportResources()
		{
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP.Properties.ImportExportResources", typeof(ImportExportResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Both.
		/// </summary>
		public static string AffectBoth
		{
			get
			{
				return ResourceManager.GetString("AffectBoth", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Game.
		/// </summary>
		public static string AffectGameFiles
		{
			get
			{
				return ResourceManager.GetString("AffectGameFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Affects:.
		/// </summary>
		public static string AffectionLabel
		{
			get
			{
				return ResourceManager.GetString("AffectionLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The selected import affection does not match with the specified files&apos; affection! Please match them!.
		/// </summary>
		public static string AffectionMissmatch
		{
			get
			{
				return ResourceManager.GetString("AffectionMissmatch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Root.
		/// </summary>
		public static string AffectRootFiles
		{
			get
			{
				return ResourceManager.GetString("AffectRootFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Tracking list:.
		/// </summary>
		public static string FilePathLabel
		{
			get
			{
				return ResourceManager.GetString("FilePathLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Export tracked files.
		/// </summary>
		public static string WindowTitleExport
		{
			get
			{
				return ResourceManager.GetString("WindowTitleExport", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Import tracking list.
		/// </summary>
		public static string WindowTitleImport
		{
			get
			{
				return ResourceManager.GetString("WindowTitleImport", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Move tracked files.
		/// </summary>
		public static string WindowTitleMove
		{
			get
			{
				return ResourceManager.GetString("WindowTitleMove", resourceCulture);
			}
		}
	}
}
