//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEWSP.Properties
{
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources
	{
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEWSP.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The game folder has been set to a new path! Would you like to update the system.cfg file to point to the new directory?.
		/// </summary>
		public static string AskGameFolderUpdateCFG
		{
			get
			{
				return ResourceManager.GetString("AskGameFolderUpdateCFG", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add.
		/// </summary>
		public static string CommonAdd
		{
			get
			{
				return ResourceManager.GetString("CommonAdd", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Apply.
		/// </summary>
		public static string CommonApply
		{
			get
			{
				return ResourceManager.GetString("CommonApply", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Save eventual changes?.
		/// </summary>
		public static string CommonAskApplyChanges
		{
			get
			{
				return ResourceManager.GetString("CommonAskApplyChanges", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Browse.
		/// </summary>
		public static string CommonBrowse
		{
			get
			{
				return ResourceManager.GetString("CommonBrowse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		public static string CommonCancel
		{
			get
			{
				return ResourceManager.GetString("CommonCancel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Copying
		///.
		/// </summary>
		public static string CommonCopying
		{
			get
			{
				return ResourceManager.GetString("CommonCopying", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Default.
		/// </summary>
		public static string CommonDefault
		{
			get
			{
				return ResourceManager.GetString("CommonDefault", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error!.
		/// </summary>
		public static string CommonError
		{
			get
			{
				return ResourceManager.GetString("CommonError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to False.
		/// </summary>
		public static string CommonFalse
		{
			get
			{
				return ResourceManager.GetString("CommonFalse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You didn&apos;t specify a filename! Pleas add one!.
		/// </summary>
		public static string CommonNoFileNameSpecified
		{
			get
			{
				return ResourceManager.GetString("CommonNoFileNameSpecified", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Notice!.
		/// </summary>
		public static string CommonNotice
		{
			get
			{
				return ResourceManager.GetString("CommonNotice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to OK.
		/// </summary>
		public static string CommonOK
		{
			get
			{
				return ResourceManager.GetString("CommonOK", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The specified path doesn&apos;t exist! Choose an existing one!.
		/// </summary>
		public static string CommonPathDoesntExist
		{
			get
			{
				return ResourceManager.GetString("CommonPathDoesntExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Remove.
		/// </summary>
		public static string CommonRemove
		{
			get
			{
				return ResourceManager.GetString("CommonRemove", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to True.
		/// </summary>
		public static string CommonTrue
		{
			get
			{
				return ResourceManager.GetString("CommonTrue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There are non existent paths inside the definitions! Changes cannot be saved!.
		/// </summary>
		public static string DCCDefChangesNotSaved
		{
			get
			{
				return ResourceManager.GetString("DCCDefChangesNotSaved", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Copy file.
		/// </summary>
		public static string DCCDefCopyFileLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefCopyFileLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current file:.
		/// </summary>
		public static string DCCDefCurrentFileLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefCurrentFileLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Program defnition:.
		/// </summary>
		public static string DCCDefDefinitionLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefDefinitionLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please choose an another name as there is already an entry named:
		/// 
		///.
		/// </summary>
		public static string DCCDefDuplicateEntry
		{
			get
			{
				return ResourceManager.GetString("DCCDefDuplicateEntry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to There is an empty program definition! Proceed (will delete empty def)?.
		/// </summary>
		public static string DCCDefEmptyDef
		{
			get
			{
				return ResourceManager.GetString("DCCDefEmptyDef", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a defition name!.
		/// </summary>
		public static string DCCDefEnterDefName
		{
			get
			{
				return ResourceManager.GetString("DCCDefEnterDefName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a name for the file.
		/// </summary>
		public static string DCCDefEnterFileName
		{
			get
			{
				return ResourceManager.GetString("DCCDefEnterFileName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Please enter a name for the program!
		///.
		/// </summary>
		public static string DCCDefEnterProgName
		{
			get
			{
				return ResourceManager.GetString("DCCDefEnterProgName", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Launch with program.
		/// </summary>
		public static string DCCDefLaunchProgLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefLaunchProgLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current program&apos;s exe:.
		/// </summary>
		public static string DCCDefProgramExeLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefProgramExeLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Program&apos;s files
		///.
		/// </summary>
		public static string DCCDefProgramFiles
		{
			get
			{
				return ResourceManager.GetString("DCCDefProgramFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Programs:.
		/// </summary>
		public static string DCCDefProgramsLabel
		{
			get
			{
				return ResourceManager.GetString("DCCDefProgramsLabel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit program definitions.
		/// </summary>
		public static string DCCDefWindowTitle
		{
			get
			{
				return ResourceManager.GetString("DCCDefWindowTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Do you want to export the tracked source files to the last exported location? Decision can be made permanent inside the application settings..
		/// </summary>
		public static string ExportOnClose
		{
			get
			{
				return ResourceManager.GetString("ExportOnClose", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Really change file extension?.
		/// </summary>
		public static string FEConfirmChangeExtension
		{
			get
			{
				return ResourceManager.GetString("FEConfirmChangeExtension", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The game launcher does not support game folders outside of the CE root. Would you like to temporarily copy the game folder into the CE root?.
		/// </summary>
		public static string GameLauchCopyToRoot
		{
			get
			{
				return ResourceManager.GetString("GameLauchCopyToRoot", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to An error occured while parsing the source tracker&apos;s ignore file list..
		/// </summary>
		public static string IgnoredRegexWrong
		{
			get
			{
				return ResourceManager.GetString("IgnoredRegexWrong", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Do you want
		/// to import the last exported filelist(s)?.
		/// </summary>
		public static string ImportOnStartup
		{
			get
			{
				return ResourceManager.GetString("ImportOnStartup", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Some regex expressions in the ignored files file, do not match any path inside the root or game directory. Maybe something was deleted or is misspelt. Please check the log for more info..
		/// </summary>
		public static string IngoredRegexDoesntExist
		{
			get
			{
				return ResourceManager.GetString("IngoredRegexDoesntExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot start process because path is not valid! Please specifiy a valif path inside the application settings!.
		/// </summary>
		public static string QuickAccesPathNonexistent
		{
			get
			{
				return ResourceManager.GetString("QuickAccesPathNonexistent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sorry, the current root directory is not a valid CE directory! Changes cannot be applied!.
		/// </summary>
		public static string RootNotValidNoSaveChanges
		{
			get
			{
				return ResourceManager.GetString("RootNotValidNoSaveChanges", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Clean project from source files
		///.
		/// </summary>
		public static string ToolsClearProcedFromSources
		{
			get
			{
				return ResourceManager.GetString("ToolsClearProcedFromSources", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Export tracked files.
		/// </summary>
		public static string ToolsExportTrackedFiles
		{
			get
			{
				return ResourceManager.GetString("ToolsExportTrackedFiles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Import tracking list.
		/// </summary>
		public static string ToolsImportTrackingList
		{
			get
			{
				return ResourceManager.GetString("ToolsImportTrackingList", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Move source files.
		/// </summary>
		public static string ToolsMoveSources
		{
			get
			{
				return ResourceManager.GetString("ToolsMoveSources", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Source tracking.
		/// </summary>
		public static string ToolsSourceTrackingSubmenu
		{
			get
			{
				return ResourceManager.GetString("ToolsSourceTrackingSubmenu", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View tracked files (game folder).
		/// </summary>
		public static string ToolsViewTrackedGameFolder
		{
			get
			{
				return ResourceManager.GetString("ToolsViewTrackedGameFolder", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View tracked files (root folder).
		/// </summary>
		public static string ToolsViewTrackedRoot
		{
			get
			{
				return ResourceManager.GetString("ToolsViewTrackedRoot", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Edit ignored files.
		/// </summary>
		public static string ToolsViewTrackerIgnoreFiles
		{
			get
			{
				return ResourceManager.GetString("ToolsViewTrackerIgnoreFiles", resourceCulture);
			}
		}
	}
}
